---
title: "Mini Project 2"
author: David Ellinger
email: "david.ellinger@gatech.edu"
abstract: |
   Daily Death Increase and the relationship with Stay at Home orders
output: github_document
---

# Background and Significance
Covid-19 has been spreading globally for most of this year, finding correlations and analyzing the data that is getting generated every day from this pandemic could help us handle the next one better than the current. 
In this project, I am going to explore the impact on daily death count from when a state gave a stay at home mandate. This could be used in the future to help dictate to other governments when it is appropriate to have this mandate.


# Problem

Is there a noticeable decrease in daily deaths after a state gave stay at home orders?

# Proposed Solution

My sample data shows all of the New England state death counts along with the dates. Each set has their dates as 30 days before the stay at home order was given and 30 days after it was lifted. 
Admittedly, the change isn’t as drastic as I would of expected (or hoped).  The following links are where they can be accessed. 


# Demo

```{r}
install.packages("pacman",repos="http://cran.us.r-project.org")
pacman::p_load(httr, jsonlite, corrplot, ggplot2, dplyr, gridExtra, install = TRUE)

generate_state_chart <- function(state, stay_at_home_start, stay_at_home_end) {
  api <- paste("api.covidtracking.com/v1/states/",c(tolower(state)),"/daily.json", sep="")
  raw_state_data <- GET(api)
  raw_state_text <- content(raw_state_data, "text")
  raw_state_json <- fromJSON(raw_state_text)
  state_data <- as.data.frame(raw_state_json)
  
  stay_at_home_start_date = as.Date(stay_at_home_start, "%Y-%m-%d") 
  stay_at_home_end_date = as.Date(stay_at_home_end, "%Y-%m-%d") 
  
  
  start = stay_at_home_start_date - 30
  end = stay_at_home_end_date + 30
  
  rect <- data.frame(xmin=stay_at_home_start_date, xmax=stay_at_home_end_date, ymin=-Inf, ymax=Inf)
  
  p <- state_data %>%
    mutate(date = as.Date(as.character(date), "%Y%m%d")) %>%
    filter(state %in% c(state))  %>%
    filter(as.Date(date, "%Y%m%d") > start) %>%
    filter(as.Date(date, "%Y%m%d") <= end) %>%
    ggplot(aes(x = date, y = deathIncrease)) + 
    geom_line() +
    xlab(paste(state, "stay at home orders (30 days before and after)")) + 
    ylab("# of Deaths/Day") +
    scale_x_date(date_breaks = "1 month",
                 date_labels = "%B")
  
  return(p + geom_rect(data=rect, aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax),
                color="grey20",
                alpha=0.5,
                inherit.aes = FALSE))
}

massachusetts = generate_state_chart("MA", "2020-04-24", "2020-05-18")
vermont = generate_state_chart("VT", "2020-03-24", "2020-05-15")
new_hampshire = generate_state_chart("NH", "2020-03-27", "2020-06-15")
maine = generate_state_chart("ME", "2020-04-02", "2020-05-31")
rhode_island = generate_state_chart("RI", "2020-03-28", "2020-05-08")
connecticut = generate_state_chart("CT", "2020-03-23", "2020-05-20")


grid.arrange(massachusetts, vermont, new_hampshire, maine, rhode_island, connecticut, ncol=2)
```

# Improvements
There is a lot that can be improved here, as far as visibility and scope of data. Applying this to all states would be difficult due to each state having autonomous guidelines. 

# References
National Academy for State Health Policy. (2020, September 10).

Chart: Each State’s COVID-19 Reopening and Reclosing Plans and Mask Requirements [Dataset]. https://www.nashp.org/governors-prioritize-health-for-all/

The COVID Tracking Project. (2020, March 1). Data API [Dataset]. https://covidtracking.com/data/api/

The R Foundation. (2020). R: The R Project for Statistical Computing. Https://Www.r-Project.Org/. https://www.r-project.org/
